---
title: "How does market power disproportionately affect the poor?"
summary: "Market power disproportionately affects the poor by making goods and services more expensive and less accessible."
author: "Prof. Anna Brown"
degree: "PhD in International Trade, University of Oxford"
tutor_type: "IB Economics Tutor"
date: 2024-08-17
---

Market power has a disproportionate impact on low-income individuals by increasing the cost and reducing the accessibility of essential goods and services.

Market power is defined as the ability of a firm or a group of firms to raise and sustain prices above the levels that would exist in a competitive market. This phenomenon often arises in monopolistic or oligopolistic markets, where a single company or a small number of companies dominate. When these firms exercise their market power, they can set prices higher than would be possible in a competitive environment, resulting in increased costs for consumers.

Low-income individuals are particularly affected by this for several reasons. First, they allocate a larger portion of their income to basic necessities such as food, housing, and utilities. As prices for these essential goods and services rise due to market power, low-income individuals experience a more significant burden since they have limited disposable income to absorb these increases.

Second, market power can lead to reduced choices and lower quality of goods and services. Firms that hold significant market power may have diminished incentives to innovate or enhance their offerings, as they face little competition. This lack of competition can result in subpar quality products, which disproportionately impacts low-income individuals who may not have the financial means to seek better alternatives.

Third, market power can contribute to greater income inequality. The profits generated by firms with substantial market power often benefit shareholders and top executives disproportionately, rather than being equitably distributed throughout the economy. This dynamic can worsen income inequality, resulting in the rich becoming richer while the poor become poorer.

Finally, market power can limit access to essential services. In sectors such as healthcare and utilities, companies with significant market power may opt to serve only the most profitable customers or regions, leaving those in economically disadvantaged areas without access to crucial services.

In summary, market power can significantly and disproportionately affect low-income individuals by raising prices, reducing choices and quality, exacerbating income inequality, and limiting access to essential services.
    