---
title: "How do negative externalities reflect a divergence between private and social costs?"
summary: "Negative externalities reflect a divergence between private and social costs as they represent the additional costs borne by society, not accounted for by private individuals or firms."
author: "Dr. Oliver White"
degree: "PhD in Public Economics, University of Edinburgh"
tutor_type: "IB Economics Tutor"
date: 2024-04-01
---

Negative externalities occur when there is a discrepancy between private and social costs, primarily because they represent the additional costs that society incurs, which are not reflected in the private costs borne by individuals or firms.

Specifically, negative externalities arise when the production or consumption of a good or service imposes costs on third parties that are not accounted for in the private cost. The private cost refers to the expenses directly incurred by the producer or consumer of a good or service. In contrast, the social cost encompasses both the private cost and the external costs imposed on society. Thus, when negative externalities are present, the social cost of production or consumption exceeds the private cost.

For example, consider a factory that produces goods while simultaneously emitting pollution as a by-product. The factory's private costs include expenses such as raw materials, labor, and other direct operational costs. However, the pollution generated by the factory leads to additional societal costs, such as increased healthcare expenses for individuals affected by the pollution and environmental cleanup costs. These costs represent the negative externalities, which are not accounted for by the factory but rather imposed on society. Consequently, the social cost of production (which is the sum of the private cost and the costs associated with negative externalities) is greater than the private cost alone.

This disparity between private and social costs can result in market failure. The existence of negative externalities implies that the market price does not accurately reflect the true costs associated with production or consumption. As a result, goods or services may be overproduced or overconsumed from a societal standpoint, leading to a reduction in overall social welfare.

In summary, negative externalities highlight the divergence between private and social costs by incorporating the additional societal costs that are overlooked in private cost calculations. This divergence can lead to market failure, as the market price fails to capture the true costs of production or consumption.
    