---
title: "What is the difference between passive and active transport across cell membranes?"
summary: "Passive transport involves the movement of substances across a membrane without energy, whereas active transport necessitates energy to move substances against their concentration gradient."
author: "Prof. Thomas Green"
degree: "PhD in Botany, University of Sheffield"
tutor_type: "IB Biology Tutor"
date: 2024-02-18
---

Passive transport is a process that occurs without the expenditure of energy, whereas active transport necessitates energy input.

### Passive Transport

Passive transport refers to the movement of molecules across a cell membrane from an area of higher concentration to an area of lower concentration. This process happens spontaneously and does not require the cell to expend energy. There are three primary types of passive transport:

1. **Diffusion**: This is the general movement of molecules from a region of high concentration to a region of low concentration.
   
2. **Osmosis**: This specifically refers to the diffusion of water molecules across a selectively permeable membrane.
   
3. **Facilitated Diffusion**: In this process, molecules traverse a membrane with the assistance of a protein channel, allowing for the movement of substances that cannot easily pass through the lipid bilayer.

### Active Transport

In contrast, active transport requires energy to move molecules across a cell membrane. This process occurs against the concentration gradient, meaning that substances are transported from an area of low concentration to an area of high concentration. There are two main types of active transport:

1. **Primary Active Transport**: This mechanism utilizes energy derived from ATP to directly move molecules across the membrane.
   
2. **Secondary Active Transport**: This method harnesses the energy generated by the movement of one molecule to propel another molecule against its concentration gradient.

### Summary

To summarize, passive transport occurs naturally and does not require energy, allowing molecules to move down their concentration gradient. In contrast, active transport requires energy input to transport molecules against their concentration gradient.
    