---
title: "How do tendons and ligaments contribute to movement?"
summary: "Tendons and ligaments contribute to movement by connecting muscles to bones and bones to each other, respectively."
author: "Dr. Megan Harris"
degree: "PhD in Cellular Biology, University College London"
tutor_type: "IB Biology Tutor"
date: 2024-06-01
---

Tendons and ligaments play vital roles in the movement of our bodies by connecting muscles to bones and linking bones to one another, respectively.

Both tendons and ligaments are types of connective tissue that are essential components of the musculoskeletal system. Tendons are tough, flexible bands of fibrous tissue that serve to attach muscles to bones. When a muscle contracts, the tendon exerts a pull on the bone, resulting in movement. This mechanism is fundamental to our bodily motion. For example, when you bend your arm, the biceps muscle in your upper arm contracts and pulls on the tendon attached to the forearm bone, which causes the arm to bend at the elbow.

Conversely, ligaments connect bones to other bones. Although they are somewhat less flexible than tendons, ligaments are specifically designed to restrict excessive movement that could potentially harm the joint. They stabilize joints and help regulate the range of motion, preventing movements that may lead to injury. For instance, the ligaments in your knee joint ensure that your knee does not bend backward.

Both tendons and ligaments are primarily composed of collagen, a robust and flexible protein. This composition enables them to endure the forces exerted upon them during movement. However, due to their limited elasticity, they can be susceptible to injury if stretched beyond their capacity.

In summary, tendons and ligaments are indispensable for human movement. Tendons transfer the force generated by contracting muscles to bones, facilitating movement, while ligaments link bones together, stabilizing joints and controlling their range of motion. Without the function of tendons and ligaments, our bodies would be unable to move in the coordinated and controlled manner that we typically experience.
    