---
title: "How do mirrors form images?"
summary: "Mirrors create images by reflecting light rays, allowing us to see clear representations of objects in front of them."
author: "Prof. David Martin"
degree: "PhD in Physics, University of Birmingham"
tutor_type: "A-Level Physics Tutor"
date: 2024-02-21
---

Mirrors produce images through the reflection of light rays.

When light rays strike a mirror, they reflect back in a predictable manner, adhering to the law of reflection. This law states that the angle of incidence, which is the angle between the incoming light ray and the normal (the line perpendicular to the mirror's surface), is equal to the angle of reflection, which is the angle between the reflected light ray and the normal. As a result, the reflected image appears to be located behind the mirror at the same distance as the object in front of it.

The image created by a mirror can be categorized as either real or virtual. A real image occurs when the reflected light rays converge at a specific point, as is the case with a concave mirror. This type of mirror is capable of focusing light and producing a sharp image. Conversely, a virtual image is produced when the reflected light rays seem to diverge from a point, as seen with flat (plane) or convex mirrors. In this instance, the image appears to be situated behind the mirror, even though it does not physically exist there.

The size and orientation of the image generated by a mirror depend on the position of the object relative to the mirror and the type of mirror used. For instance, convex mirrors create smaller and upright images, while concave mirrors can produce larger and inverted images. Understanding the principles of image formation by mirrors is essential across various fields, including optics, astronomy, medicine, and engineering.
    