---
title: "How can you calculate the electric field of a uniformly charged disk?"
summary: "To calculate the electric field of a uniformly charged disk, use the formula for electric field due to a ring."
author: "Prof. Sophia Clark"
degree: "PhD in Nuclear Physics, University of Leeds"
tutor_type: "A-Level Physics Tutor"
date: 2024-07-16
---

To calculate the electric field produced by a uniformly charged disk, we can leverage the formula for the electric field generated by a ring of charge.

A uniformly charged disk can be conceptualized as a series of concentric rings. To determine the electric field at a point along the axis of the disk, we utilize the electric field formula for a ring, which is expressed as:

$$
E = \frac{kQ}{r^2} \sin(\theta)
$$

In this equation:
- $E$ represents the electric field at a specific point along the axis of the ring,
- $k$ is the Coulomb's constant,
- $Q$ denotes the charge of the ring,
- $r$ is the distance from the center of the ring to the point on the axis,
- $\theta$ is the angle formed between the axis and a line that is perpendicular to the plane of the ring.

To find the total electric field due to the entire disk, we need to integrate this expression over all the infinitesimally thin rings that make up the disk. The charge on each ring is proportional to its area, and the distance from the center of each ring to the point on the axis remains constant for all rings. This allows us to simplify the integral, resulting in the electric field at a point along the axis of the disk being given by:

$$
E = \frac{kQ}{2R^2} (1 - \cos(\theta))
$$

Here, $R$ is the radius of the disk, and $\theta$ is the angle between the axis and a line perpendicular to the plane of the disk.

This formula provides the electric field at any point along the axis of a uniformly charged disk. It is important to note that the electric field at the center of the disk is zero, as the contributions from all the concentric rings cancel each other out at that point.
    