---
title: "What is a real and virtual image?"
summary: "A real image is formed when light rays converge to a point, whereas a virtual image is formed when light rays appear to diverge from a point."
author: "Prof. Isabella Taylor"
degree: "PhD in Quantum Computing, University College London"
tutor_type: "A-Level Physics Tutor"
date: 2024-06-10
---

A real image is produced when light rays converge at a specific point, while a virtual image occurs when light rays appear to diverge from a point.

Both real and virtual images can be generated through the use of lenses or mirrors. A real image is created when light rays converge after passing through a lens or reflecting off a mirror. This type of image can be projected onto a screen and is always inverted. For instance, real images can also be formed by concave mirrors when the object is positioned beyond the focal point. In this scenario, the resulting image is real, inverted, and smaller than the object itself.

Conversely, a virtual image is formed when light rays seem to diverge from a point after passing through a lens or reflecting off a mirror. Unlike real images, virtual images cannot be projected onto a screen and are always upright. Virtual images are typically generated by convex mirrors and concave lenses when the object is located between the lens or mirror and the focal point. In such cases, the image is virtual, upright, and often larger than the object.

The distinctions between real and virtual images are significant, as they possess different properties and are formed through different optical processes. Understanding these differences is crucial in the field of optics and can greatly aid in the design of various optical instruments, such as cameras and telescopes.
    