---
title: "What is the principle of electromagnetic waves?"
summary: "Electromagnetic waves are transverse waves characterized by oscillating electric and magnetic fields."
author: "Prof. Alan Smith"
degree: "PhD in Physics, University of Cambridge"
tutor_type: "A-Level Physics Tutor"
date: 2024-05-03
---

Electromagnetic waves are a specific type of transverse wave characterized by oscillating electric and magnetic fields.

These waves play a crucial role in the electromagnetic spectrum, which encompasses a wide range of phenomena, including radio waves, microwaves, infrared radiation, visible light, ultraviolet radiation, X-rays, and gamma rays. Electromagnetic waves are generated by the acceleration of charged particles, such as electrons, and are capable of traveling through a vacuum at the speed of light, denoted as $c$, where $c \approx 3 \times 10^8 \, \text{m/s}$.

The foundation of electromagnetic wave behavior lies in Maxwell's equations, a set of four fundamental equations that define the relationship between electric fields, magnetic fields, and their sources. These equations illustrate that a changing electric field induces a magnetic field, while a changing magnetic field induces an electric field. This interplay creates a self-sustaining cycle of electric and magnetic fields, which propagates through space as an electromagnetic wave.
    