---
title: "How does electromagnetic induction produce an electric current?"
summary: "Electromagnetic induction generates electric current by inducing voltage in a conductor, enabling the conversion of magnetic energy into electrical energy."
author: "Prof. Peter Brown"
degree: "PhD in Mathematics, University of Warwick"
tutor_type: "IB Physics Tutor"
date: 2024-04-14
---

Electromagnetic induction is the process by which an electric current is generated by inducing a voltage within a conductor.

This phenomenon occurs when a conductor is either moved through a magnetic field or when the magnetic field itself is moved relative to the conductor. The resulting voltage induced in the conductor is directly proportional to the rate of change of the magnetic field or the speed at which the conductor is moved.

According to Ohm's law, this induced voltage causes an electric current to flow through the conductor. The direction of the current is determined by both the orientation of the induced voltage and the resistance of the conductor. This principle is fundamental to the operation of devices such as generators and transformers.

In generators, a mechanical force is applied to rotate a coil of wire within a magnetic field. As the magnetic field changes, a voltage is induced in the coil, leading to the flow of electric current. This current is subsequently used to power various electrical devices.

Transformers, on the other hand, consist of two coils of wire positioned close to one another without physical contact. When an alternating current flows through one coil, it creates a varying magnetic field. This changing magnetic field induces a voltage in the second coil, resulting in an electric current. Transformers are crucial for altering the voltage of alternating currents, which is essential for the efficient distribution of electrical power.

In summary, electromagnetic induction is a fundamental principle of electricity with a wide array of applications, including power generation and wireless charging.
    