---
title: "What is Huygens' principle?"
summary: "Huygens' principle asserts that each point on a wavefront acts as a source of secondary waves, contributing to the propagation of the overall wave."
author: "Prof. Richard White"
degree: "PhD in Mathematics, University of Leicester"
tutor_type: "A-Level Physics Tutor"
date: 2024-02-09
---

Huygens' principle is a foundational concept in wave theory, introduced by the Dutch physicist Christiaan Huygens in the 17th century. This principle posits that every point on a wavefront can be regarded as a source of secondary waves, which propagate outward in all directions at the same speed as the original wave.

The essence of Huygens' principle lies in the notion that waves are generated by the continuous emission of new waves from each point along the wavefront. Consequently, the wavefront can be visualized as a collection of infinitesimal wavelets, each spreading in all directions and interacting with the surrounding wavelets.

A significant implication of Huygens' principle is its ability to elucidate the phenomenon of diffraction. Diffraction occurs when waves encounter an obstacle or pass through a narrow aperture. In such scenarios, the original wavefront is altered, and secondary waves emerge from every point of the new wavefront. This results in the wave spreading out and bending around the obstacle or aperture.

Overall, Huygens' principle serves as a powerful framework for understanding wave behavior and finds applications across various fields, including optics, acoustics, seismology, and oceanography.
    