---
title: "What is a linear accelerator used for?"
summary: "A linear accelerator is used to accelerate charged particles to high energies for use in various applications."
author: "Prof. Sophia Clark"
degree: "PhD in Nuclear Physics, University of Leeds"
tutor_type: "A-Level Physics Tutor"
date: 2024-03-20
---

A linear accelerator, commonly referred to as a linac, is a device designed to accelerate charged particles to high energies for a wide range of applications.

Linacs play a crucial role in various fields, including medicine, industry, and scientific research. In the medical field, linacs are primarily utilized in radiation therapy to treat cancer patients. The high-energy particles generated by the linac are precisely directed towards cancerous cells, effectively destroying them while minimizing damage to surrounding healthy tissue. In industrial settings, linacs are employed for material inspection and modification processes, such as sterilizing medical equipment or altering the properties of polymers. Additionally, in scientific research, linacs are instrumental in studying the fundamental properties of matter and in the creation of new materials.

The fundamental design of a linac consists of a series of accelerating structures that employ radiofrequency (RF) fields to accelerate charged particles, which can include electrons or protons. Particles are injected into the linac and traverse through these accelerating structures, gaining energy at each stage. The final energy of the accelerated particles can vary significantly, typically ranging from a few million electron volts (MeV) to several billion electron volts (GeV), depending on the specific application.

Linacs can be configured to produce either a continuous beam of particles or a pulsed beam, based on the requirements of the application. They can also be integrated with other technologies, such as magnets, which are used to steer and focus the particle beam.

In summary, linear accelerators are versatile instruments that enable the acceleration of charged particles to high energies, serving a diverse array of applications including cancer treatment, material modification, and scientific exploration.
    