---
title: "What is the pattern in the sequence 3, 6, 12, 24?"
summary: "The sequence 3, 6, 12, 24 follows a pattern where each term is double the preceding term."
author: "Dr. Angela Davis"
degree: "MSc in Mathematics, University of Bristol"
tutor_type: "GCSE Maths Tutor"
date: 2024-07-25
---

The sequence given, $ 3, 6, 12, 24 $, follows a clear pattern: each term is double the previous term.

Let’s analyze this sequence more thoroughly by examining its terms: $ 3, 6, 12, $ and $ 24 $. By comparing each term with the one preceding it, we observe the following relationships: $ 6 $ is obtained by multiplying $ 3 $ by $ 2 $, $ 12 $ is $ 6 $ multiplied by $ 2 $, and $ 24 $ is $ 12 $ multiplied by $ 2 $. This consistent doubling indicates that each term is derived by multiplying the previous term by $ 2 $.

This type of sequence is classified as a geometric sequence, where each term is generated by multiplying the preceding term by a constant factor. In this case, the constant factor is $ 2 $. The first term of the sequence is $ 3 $, and the common ratio— the factor by which we multiply each term— is $ 2 $.

To find any term in this geometric sequence, we can use the formula for the $ n $-th term, which is given by:

$$
a_n = a \times r^{(n-1)}
$$

In this formula, $ a $ represents the first term, $ r $ is the common ratio, and $ n $ is the term number. For our specific sequence, we have $ a = 3 $ and $ r = 2 $. 

For instance, if we want to calculate the $ 5 $-th term, we apply the formula as follows:

$$
a_5 = 3 \times 2^{(5-1)} = 3 \times 16 = 48
$$

Understanding this pattern enhances our ability to predict future terms and analyze the sequence more effectively.
    