---
title: "How can we classify earthquakes based on their depth of focus?"
summary: "Earthquakes can be classified into three types based on their depth of focus: shallow, intermediate, and deep-focus earthquakes."
author: "Dr. Thomas Lee"
degree: "PhD in Urban Studies, University of Cambridge"
tutor_type: "IB Geography Tutor"
date: 2024-07-15
---

Earthquakes can be categorized into three distinct types based on their depth of focus: shallow-focus, intermediate-focus, and deep-focus earthquakes.

**Shallow-focus earthquakes** are the most prevalent, constituting approximately $75\%$ of all seismic activity. These earthquakes occur at depths of less than $70$ kilometers below the Earth's surface. They are often the most destructive because their epicenters—the points on the Earth's surface directly above the focus—are situated close to the surface. This proximity allows seismic waves to travel a shorter distance before reaching the surface, resulting in stronger shaking and potentially greater damage.

**Intermediate-focus earthquakes** occur at depths ranging from $70$ to $300$ kilometers and represent about $20\%$ of all earthquakes. The seismic waves generated by these earthquakes must traverse a greater distance to reach the surface, which can diminish their destructive potential. Nonetheless, they can still inflict considerable damage, especially if they happen near populated areas.

**Deep-focus earthquakes** are the least common, accounting for roughly $5\%$ of all earthquakes. These events occur at depths exceeding $300$ kilometers, with some reaching as deep as $700$ kilometers. Despite their significant depth, deep-focus earthquakes can still be felt at the surface; however, their effects are generally less severe than those of shallow or intermediate-focus earthquakes. The mechanisms behind deep-focus earthquakes remain somewhat enigmatic, as the extreme pressure and temperature at such depths are thought to inhibit the frictional sliding typically associated with seismic activity.

The depth of an earthquake's focus is influenced by the tectonic activity that generates it. Shallow-focus earthquakes predominantly occur at divergent and transform boundaries, where tectonic plates are either moving apart or sliding past one another. In contrast, intermediate and deep-focus earthquakes are more frequently found at convergent boundaries, where one tectonic plate is forced beneath another in a process known as subduction. As the descending plate penetrates deeper into the Earth's mantle, it can trigger seismic events.

In summary, the depth of an earthquake's focus plays a crucial role in determining its potential for destruction. By gaining insight into the various types of earthquakes and the tectonic processes that induce them, we can enhance our ability to predict and prepare for these natural disasters.
    