---
title: "How does crystal field theory apply to transition metal complexes?"
summary: "Crystal field theory explains the colour, magnetic properties, and structures of transition metal complexes."
author: "Prof. Lily Johnson"
degree: "PhD in Environmental Chemistry, University of Edinburgh"
tutor_type: "IB Chemistry Tutor"
date: 2024-06-07
---

Crystal field theory (CFT) provides a framework for understanding the color, magnetic properties, and structures of transition metal complexes.

CFT is a theoretical model that describes how the degeneracy of electron orbital states, primarily the $d$ or $f$ orbitals, is broken due to the influence of a static electric field generated by a surrounding charge distribution. This model is particularly applicable to transition metal complexes, which are characterized by their incompletely filled $d$ orbitals. These $d$ orbitals are capable of accepting electrons from ligands, thereby forming coordination complexes.

In the context of transition metal complexes, the charge distribution around the metal ion is contributed by the ligands—ions or molecules that donate electron pairs to the metal. As the ligands approach the metal ion, they exert an electric field that affects the degenerate (same-energy) $d$ orbitals of the metal. This interaction results in the splitting of the $d$ orbitals into two sets with different energy levels. The degree of this splitting is influenced by both the nature of the ligands and the geometry of the complex.

The splitting of the $d$ orbitals accounts for several properties of transition metal complexes. For example, the observed color of these complexes arises from the absorption of specific wavelengths of light, which corresponds to the energy difference between the split $d$ orbitals. When light is absorbed, an electron is promoted from a lower-energy $d$ orbital to a higher-energy one. The wavelengths of light that are not absorbed are either transmitted or reflected, resulting in the color that we perceive.

In addition, the magnetic properties of transition metal complexes can be elucidated through CFT. A complex with unpaired electrons in its $d$ orbitals will exhibit paramagnetism, meaning it is attracted to a magnetic field. Conversely, if all electrons in the $d$ orbitals are paired, the complex will be diamagnetic, showing no attraction to a magnetic field.

Finally, CFT also allows for predictions regarding the structure of the complex, such as whether it adopts a tetrahedral, square planar, or octahedral geometry. The geometry that minimizes the overall energy of the complex is the one that will be favored. This low-energy configuration is determined by the arrangement of the ligands around the metal ion, which aims to minimize repulsion between the electrons in the $d$ orbitals and the negative charge of the ligands.
    