---
title: "How is potential energy stored in a spring?"
summary: "Potential energy is stored in a spring through the work done in stretching or compressing it from its equilibrium position."
author: "Prof. Emma Johnson"
degree: "PhD in Condensed Matter Physics, University of Bristol"
tutor_type: "IB Physics Tutor"
date: 2024-08-09
---

Potential energy in a spring is generated by the work done to stretch or compress it from its equilibrium position.

When a spring is either stretched or compressed, it accumulates potential energy. This phenomenon is described by Hooke's Law, which asserts that the force required to extend or compress a spring by a certain distance is directly proportional to that distance. In simpler terms, the greater the stretch or compression, the more force you must exert. The force applied performs work on the spring, and this work is stored as potential energy.

The potential energy (PE) stored in a spring can be expressed by the formula:

$$
PE = \frac{1}{2} k x^2
$$

In this equation, $k$ represents the spring constant, which indicates the stiffness of the spring, and $x$ denotes the displacement from the spring's equilibrium position. This relationship reveals that the potential energy stored in a spring is directly proportional to the square of the displacement. Consequently, if the displacement is doubled, the potential energy increases by a factor of four.

Upon releasing the spring, the stored potential energy transforms into kinetic energy as the spring reverts to its equilibrium position. This process exemplifies the conservation of energy, a fundamental principle in physics that dictates that energy cannot be created or destroyed, only transformed or transferred from one form to another.

In summary, potential energy is stored in a spring through the work done in either stretching or compressing it. The quantity of energy stored is proportional to the square of the displacement from the equilibrium position, as outlined by the equation:

$$
PE = \frac{1}{2} k x^2
$$

This stored energy can subsequently be converted into other forms of energy, such as kinetic energy, when the spring is released.
    