---
title: "Describe the motion under balanced forces"
summary: "Under balanced forces, an object either remains at rest or continues to move at a constant velocity."
author: "Prof. Mia Turner"
degree: "PhD in Quantum Mechanics, University of Oxford"
tutor_type: "IB Physics Tutor"
date: 2024-03-28
---

In the presence of balanced forces, an object will either remain stationary or continue to move at a constant velocity.

The concept of balanced forces is essential in the study of motion in physics. When the forces acting on an object are balanced, it indicates that the net force—the vector sum of all forces acting on the object—is zero. This equilibrium state allows the object to either stay at rest or to move at a constant speed in a straight line. This principle aligns with Newton's first law of motion, often referred to as the law of inertia. According to this law, an object at rest will remain at rest, and an object in motion will continue to move at the same speed and in the same direction, unless it is influenced by an unbalanced force.

For example, consider a book resting on a table. The force of gravity acting downward on the book is countered by the normal force exerted by the table acting upward. Since these forces are equal in magnitude and opposite in direction, they effectively cancel each other out, resulting in a net force of zero. As a result, the book remains at rest.

In another scenario, if a car is traveling at a constant speed along a straight road, the forces acting on it are also balanced. The forward force generated by the car's engine is opposed by the combined effects of air resistance and friction between the tires and the road. Again, since these forces are equal and opposite, they cancel each other out, resulting in a net force of zero. Consequently, the car continues to move at a constant speed in a straight line.

It is important to recognize that if any additional force acts on the object, the forces become unbalanced, leading to a change in the object's state of motion. For instance, if you apply a push to the book on the table, the forces become unbalanced, causing the book to move. Similarly, if the car's engine increases its force output or if the forces of friction or air resistance change, the car will either accelerate, decelerate, or alter its direction.

In summary, balanced forces play a critical role in maintaining an object's state of motion, whether it is at rest or moving at a constant velocity.
    