---
title: "Why are tungsten filaments used in incandescent bulbs?"
summary: "Tungsten filaments are used in incandescent bulbs due to their high melting point and resistance to heat."
author: "Prof. Emma Johnson"
degree: "PhD in Condensed Matter Physics, University of Bristol"
tutor_type: "IB Physics Tutor"
date: 2024-03-29
---

Tungsten filaments are commonly used in incandescent light bulbs because of their exceptional melting point and heat resistance.

Tungsten is the metal with the highest melting point among all elements, making it the ideal choice for filaments in incandescent bulbs. These filaments must be heated to extremely high temperatures in order to emit light. Tungsten’s ability to endure these high temperatures without melting is crucial for the functionality of incandescent lighting.

The operation of the filament involves passing an electric current through it. This current causes the filament to heat up and glow, a phenomenon known as incandescence. To achieve this, the filament material must be able to tolerate the significant heat generated by the electric current, which is why tungsten, with its high melting point, is preferred.

In addition to its high melting point, tungsten exhibits high electrical resistance. This characteristic means that a substantial amount of energy is required to pass an electric current through the filament, resulting in increased heat generation. It is this heat that causes the filament to glow and produce light.

Moreover, tungsten is an effective conductor of heat, allowing it to efficiently distribute the heat generated by the electric current throughout the filament. This property ensures that the filament glows uniformly, resulting in a steady and consistent light output.

Tungsten also has a low coefficient of thermal expansion, which means it does not expand significantly when heated. This is a critical feature because excessive expansion could lead to breaking or deforming the filament, ultimately causing the light bulb to fail.

Finally, tungsten is relatively abundant and inexpensive, making it a cost-effective option for incandescent bulbs. Despite the rise of more energy-efficient lighting alternatives, such as compact fluorescent lamps (CFLs) and light-emitting diodes (LEDs), tungsten filaments remain widely used in incandescent bulbs due to their advantageous properties.
    