---
title: "Why are two light waves sometimes incoherent?"
summary: "Two light waves are sometimes incoherent because they do not maintain a constant phase relationship with each other."
author: "Prof. Mia Turner"
degree: "PhD in Quantum Mechanics, University of Oxford"
tutor_type: "IB Physics Tutor"
date: 2024-02-11
---

Two light waves can sometimes be classified as incoherent when they do not maintain a constant phase relationship with one another.

Coherence, in more detail, refers to the degree of correlation between the phases of two or more waves. When light waves are coherent, they exhibit a constant phase difference and share the same frequency. This coherence allows for constructive or destructive interference, resulting in the formation of an interference pattern. This principle underlies many optical phenomena and technologies, including lasers and holography.

Conversely, two light waves may be incoherent, indicating that they do not maintain a stable phase relationship. Several factors can contribute to this incoherence. First, if the light waves originate from different sources that are not phase-locked, they will be incoherent. For example, light emitted from the sun or a light bulb is typically incoherent because it is generated by numerous independent atoms, each emitting light with its own random phase.

Second, even if the light waves come from the same source, they can become incoherent if they travel along different paths. The phase of a light wave changes as it propagates, influenced by the medium through which it travels and the length of its path. If the path lengths or the properties of the media vary, the phase relationship between the waves will fluctuate over time, leading to incoherence.

Lastly, the temporal stability of the light source can also affect coherence. If the frequency of the light varies over time, the phase relationship between different segments of the wave will not remain constant, resulting in temporal incoherence.

It is important to note that incoherence is not inherently negative; in fact, it is crucial for certain applications. For instance, incoherent light is employed in imaging systems such as microscopes and telescopes. This type of light provides uniform illumination and prevents the formation of interference patterns, which could otherwise distort the resulting images.
    